version: '3'
services:
  backend:
    container_name: blazor_blog
    build: ./src
    ports:
      - 8080:8080
    environment:
      - DBHOST=blazor-blog
      - DBSERVER=db
      # - DB_PORT=1433
      # - DB_USER=sa
      - DBPASSWORD=BlazingBlog1234!
    restart: 'always'
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: blazor-blog-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BlazingBlog1234!
      - MSSQL_PID=Developer
    restart: 'always'